sonar.projectKey=aah-22_commanders
sonar.organization=aah-22

sonar.sources=api,ingest,models,db,web/src
sonar.tests=tests,web/src
sonar.test.inclusions=web/src/**/*.spec.ts
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.javascript.lcov.reportPaths=web/coverage/web/lcov.info

sonar.exclusions=**/__pycache__/**,docs/**,db/migrations/**,web/node_modules/**,web/dist/**,web/.angular/**
