"""The nflverse assets this project mirrors: loader, key, release URL (for MLflow lineage) and the columns kept.

Everything comes through `nflreadpy`; URLs are the public nflverse-data release files the loaders read, recorded as
the dataset `source` in MLflow so a run says exactly where its rows came from. Spread / total / moneyline columns are
deliberately absent: this is not a betting site.
"""

from __future__ import annotations

RELEASES = "https://github.com/nflverse/nflverse-data/releases/download"

PBP_COLUMNS = [
    "game_id",
    "play_id",
    "season",
    "week",
    "posteam",
    "defteam",
    "home_team",
    "away_team",
    "fixed_drive",
    "drive",
    "qtr",
    "down",
    "ydstogo",
    "yardline_100",
    "goal_to_go",
    "game_seconds_remaining",
    "half_seconds_remaining",
    "play_type",
    "desc",
    "yards_gained",
    "epa",
    "qb_epa",
    "success",
    "wp",
    "wpa",
    "air_yards",
    "yards_after_catch",
    "pass",
    "rush",
    "qb_dropback",
    "qb_scramble",
    "qb_kneel",
    "qb_spike",
    "shotgun",
    "no_huddle",
    "passer_player_id",
    "rusher_player_id",
    "receiver_player_id",
    "penalty_player_id",
    "sack",
    "qb_hit",
    "interception",
    "fumble_lost",
    "touchdown",
    "penalty",
    "cpoe",
    "xpass",
    "pass_location",
    "run_location",
    "series",
    "series_success",
    "fixed_drive_result",
    "complete_pass",
    "incomplete_pass",
    "first_down",
    "td_team",
    "posteam_score",
    "defteam_score",
    "score_differential",
    "total_home_score",
    "total_away_score",
    "aborted_play",
]

GAME_COLUMNS = [
    "game_id",
    "season",
    "game_type",
    "week",
    "gameday",
    "weekday",
    "gametime",
    "away_team",
    "away_score",
    "home_team",
    "home_score",
    "location",
    "result",
    "total",
    "overtime",
    "div_game",
    "roof",
    "surface",
    "temp",
    "wind",
    "away_qb_id",
    "home_qb_id",
    "away_qb_name",
    "home_qb_name",
    "away_coach",
    "home_coach",
    "stadium",
    "away_rest",
    "home_rest",
]

PLAYER_COLUMNS = [
    "gsis_id",
    "display_name",
    "first_name",
    "last_name",
    "football_name",
    "esb_id",
    "pfr_id",
    "pff_id",
    "otc_id",
    "espn_id",
    "birth_date",
    "position_group",
    "position",
    "height",
    "weight",
    "college_name",
    "jersey_number",
    "rookie_season",
    "last_season",
    "latest_team",
    "status",
    "years_of_experience",
    "draft_year",
    "draft_round",
    "draft_pick",
    "draft_team",
    "headshot",
]

TEAM_COLUMNS = [
    "team_abbr",
    "team_name",
    "team_id",
    "team_nick",
    "team_conf",
    "team_division",
    "team_color",
    "team_color2",
    "team_logo_wikipedia",
    "team_logo_espn",
    "team_wordmark",
]

PLAYER_STAT_COLUMNS = [
    "player_id",
    "player_display_name",
    "position",
    "position_group",
    "season",
    "week",
    "season_type",
    "game_id",
    "team",
    "opponent_team",
    "completions",
    "attempts",
    "passing_yards",
    "passing_tds",
    "passing_interceptions",
    "sacks_suffered",
    "sack_yards_lost",
    "passing_air_yards",
    "passing_yards_after_catch",
    "passing_first_downs",
    "passing_epa",
    "passing_cpoe",
    "pacr",
    "carries",
    "rushing_yards",
    "rushing_tds",
    "rushing_fumbles_lost",
    "rushing_first_downs",
    "rushing_epa",
    "receptions",
    "targets",
    "receiving_yards",
    "receiving_tds",
    "receiving_fumbles_lost",
    "receiving_air_yards",
    "receiving_yards_after_catch",
    "receiving_first_downs",
    "receiving_epa",
    "racr",
    "target_share",
    "air_yards_share",
    "wopr",
    "def_tackles_solo",
    "def_tackles_with_assist",
    "def_tackle_assists",
    "def_tackles_for_loss",
    "def_fumbles_forced",
    "def_sacks",
    "def_qb_hits",
    "def_interceptions",
    "def_pass_defended",
    "def_tds",
]

# nflverse team-week stats: the cross-check for gm.team_game_summary (its passing_epa / rushing_epa follow the
# nflverse convention, see ingest/derive/filters.py). The fg_*_list / distance string columns are not kept.
TEAM_GAME_STAT_COLUMNS = [
    "season",
    "week",
    "team",
    "season_type",
    "game_id",
    "opponent_team",
    "completions",
    "attempts",
    "passing_yards",
    "passing_tds",
    "passing_interceptions",
    "sacks_suffered",
    "sack_yards_lost",
    "sack_fumbles_lost",
    "passing_air_yards",
    "passing_yards_after_catch",
    "passing_first_downs",
    "passing_epa",
    "passing_cpoe",
    "carries",
    "rushing_yards",
    "rushing_tds",
    "rushing_fumbles_lost",
    "rushing_first_downs",
    "rushing_epa",
    "receptions",
    "targets",
    "receiving_yards",
    "receiving_tds",
    "receiving_fumbles_lost",
    "receiving_first_downs",
    "receiving_epa",
    "special_teams_tds",
    "def_tackles_for_loss",
    "def_fumbles_forced",
    "def_sacks",
    "def_qb_hits",
    "def_interceptions",
    "def_pass_defended",
    "def_tds",
    "def_safeties",
    "penalties",
    "penalty_yards",
    "fumbles_lost_total",
    "fg_made",
    "fg_att",
    "pat_made",
    "pat_att",
    "pt_att",
    "pt_net_yards",
]

# name → (release URL, natural key)
SOURCES: dict[str, tuple[str, list[str]]] = {
    "teams": (f"{RELEASES}/teams/teams.csv", ["team_abbr"]),
    "players": (f"{RELEASES}/players/players.parquet", ["gsis_id"]),
    "games": (f"{RELEASES}/schedules/games.rds", ["game_id"]),
    "plays": (f"{RELEASES}/pbp/play_by_play_{{season}}.parquet", ["game_id", "play_id"]),
    "player_game_stats": (f"{RELEASES}/stats_player/stats_player_week_{{season}}.parquet", ["player_id", "game_id"]),
    "team_game_stats": (f"{RELEASES}/stats_team/stats_team_week_{{season}}.parquet", ["team", "game_id"]),
    "snap_counts": (f"{RELEASES}/snap_counts/snap_counts_{{season}}.parquet", ["pfr_player_id", "game_id"]),
    "rosters_weekly": (
        f"{RELEASES}/weekly_rosters/roster_weekly_{{season}}.parquet",
        ["season", "week", "team", "gsis_id"],
    ),
    "depth_charts": (
        f"{RELEASES}/depth_charts/depth_charts_{{season}}.parquet",
        ["season", "week", "team", "gsis_id", "pos_abb"],
    ),
    "injuries": (f"{RELEASES}/injuries/injuries_{{season}}.parquet", ["season", "week", "game_type", "gsis_id"]),
    "contracts": (f"{RELEASES}/contracts/historical_contracts.parquet", ["otc_id", "year_signed", "team_raw"]),
    "contract_seasons": (
        f"{RELEASES}/contracts/historical_contracts.parquet",
        ["otc_id", "year_signed", "team_raw", "season"],
    ),
    "draft_picks": (f"{RELEASES}/draft_picks/draft_picks.parquet", ["season", "round", "pick"]),
    "trades": (f"{RELEASES}/trades/trades.parquet", ["trade_id", "seq"]),
    "pfr_def_game": (f"{RELEASES}/pfr_advstats/advstats_week_def.parquet", ["pfr_player_id", "game_id"]),
    "pfr_pass_game": (f"{RELEASES}/pfr_advstats/advstats_week_pass.parquet", ["pfr_player_id", "game_id"]),
    "pfr_rush_game": (f"{RELEASES}/pfr_advstats/advstats_week_rush.parquet", ["pfr_player_id", "game_id"]),
    "pfr_rec_game": (f"{RELEASES}/pfr_advstats/advstats_week_rec.parquet", ["pfr_player_id", "game_id"]),
    "ngs_passing": (
        f"{RELEASES}/nextgen_stats/ngs_passing.parquet",
        ["season", "season_type", "week", "player_gsis_id"],
    ),
    "ngs_rushing": (
        f"{RELEASES}/nextgen_stats/ngs_rushing.parquet",
        ["season", "season_type", "week", "player_gsis_id"],
    ),
    "ngs_receiving": (
        f"{RELEASES}/nextgen_stats/ngs_receiving.parquet",
        ["season", "season_type", "week", "player_gsis_id"],
    ),
}

FIRST_SEASON = 2016  # participation (pressure / coverage / personnel) starts here; everything else goes back further
